src/tilda/Gen.java
src/tilda/parsing/parts/Documentation.java
src/tilda/parsing/parts/Schema.java
src/tilda/utils/GraphvizUtil.java

V2 Pull Request

---

src/tilda/generation/graphviz/GraphvizUtil.java

CSS SVG alignments.

---

src/tilda/generation/graphviz/GraphvizUtil.java

Visual enhancements, colors as per Tilda Graphviz scrapbook.

---

src/tilda/generation/graphviz/GraphvizUtil.java

Graphviz improvements for complex schema

---

src/tilda/grammar/servlets/TildaSQLServlet.java

Sql antlr<Bug fixes>

---

docs/chrome-extension/css/custom.css
docs/chrome-extension/js/core/relation_renderer.js
docs/chrome-extension/js/views/tilda_schema_view.js
src/tilda/generation/html/DocGen.java

Generating java doc by embedding html generated from chrome app.
@ldhasson Please review

Tilda chrome extension saves as html

---

src/tilda/generation/graphviz/GraphvizUtil.java
src/tilda/generation/html/DocGen.java
src/tilda/generation/html/Docs.java

Add Search in tilda generated documentation.

Feature search docs

---

docs/chrome-extension/js/boot.js
docs/chrome-extension/js/core/helpers.js
docs/chrome-extension/js/core/parser.js
docs/chrome-extension/js/core/read_schema.js
docs/chrome-extension/js/core/relation_renderer.js
docs/chrome-extension/js/templates/tilda_schema/_new.html
docs/chrome-extension/js/views/tilda_schema_view.js

Visualization of entire dependencies

---

src/tilda/generation/html/Docs.java

Feature visualize docs

---

src/tilda/utils/DurationUtil.java
src/tilda/utils/SessionUtil.java

- Additional SessionUtil Attributes

Added helper methods -- duration util

---

src/tilda/data/_Tilda/TILDA__CONNECTION.java
src/tilda/data/_Tilda/TILDA__JOBS.java
src/tilda/data/_Tilda/TILDA__JOB_DETAIL.java
src/tilda/data/_Tilda/TILDA__KEY.java
src/tilda/data/_Tilda/TILDA__MAINTENANCE.java
src/tilda/data/_Tilda/TILDA__MAPPING.java
src/tilda/data/_Tilda/TILDA__OBJECTPERF.java
src/tilda/data/_Tilda/TILDA__REFILLPERF.java
src/tilda/data/_Tilda/TILDA__TESTING.java
src/tilda/data/_Tilda/TILDA__TESTING_Factory.java
src/tilda/data/_Tilda/TILDA__TRANSPERF.java
src/tilda/data/_Tilda/TILDA__ZONEINFO.java
src/tilda/data/_Tilda/TILDA___Docs.TILDA.html
src/tilda/data/_tilda.Tilda.json
src/tilda/generation/java8/TildaData.java

Also updated TILDA.TESTING and regenerated tilda classes.

#98 protect=SMART causing compile errors

---

src/tilda/data/_Tilda/TILDA__1_0.java
src/tilda/data/_Tilda/TILDA__CONNECTION.java
src/tilda/data/_Tilda/TILDA__JOBS.java
src/tilda/data/_Tilda/TILDA__JOB_DETAIL.java
src/tilda/data/_Tilda/TILDA__KEY.java
src/tilda/data/_Tilda/TILDA__MAINTENANCE.java
src/tilda/data/_Tilda/TILDA__MAPPING.java
src/tilda/data/_Tilda/TILDA__OBJECTPERF.java
src/tilda/data/_Tilda/TILDA__REFILLPERF.java
src/tilda/data/_Tilda/TILDA__TESTING.java
src/tilda/data/_Tilda/TILDA__TRANSPERF.java
src/tilda/data/_Tilda/TILDA__ZONEINFO.java
src/tilda/data/_Tilda/TILDA___Docs.TILDA.html
src/tilda/data/_Tilda/TILDA___PostgreSQL.TILDA.sql
src/tilda/data/_tilda.Tilda.json
src/tilda/parsing/parts/Object.java

Fixed a simple issue in the code, and added the object "Testing2" to the
main Tilda json file as a test. Confirmed that SQL was generated, but no
Java code.
Main code change is in /Tilda/src/tilda/parsing/parts/Object.java. All other changes in this commit are due to the Gen.

Issue #106 with dbOnly not working for objects

---

src/tilda/utils/MailUtil.java

Issue #113 updating MailUtil to handle StartTLS

---

src/tilda/generation/html/Docs.java

- Removed dependency on @NotNull from unsupported JDK feature.

---

src/tilda/utils/TextUtil.java

Issue #119 adding new support for isNullOrEmpty on string lists.

Issue #119 adding TextUtil.isNullOrEmpty(List<String>)

---

src/tilda/generation/html/Docs.java

columns for dbOnly objects/views.
Issue #122... Changed code to not output JavaType, Mode, Protect and Invariant columns in docs for dbOnly objects and views.

Simple fix for #122. Removed JavaType, Mode, Protect and Invariant

---

docs/chrome-extension/js/core/parser.js
docs/chrome-extension/js/core/parser_element.js
docs/chrome-extension/js/lib/graphlib.core.js
docs/chrome-extension/js/lib/require.js
docs/chrome-extension/js/views/tilda_schema_view.js

Chrome extention bug fixes

---

docs/chrome-extension/js/core/parser.js
docs/chrome-extension/js/core/relation_renderer.js

#137  “sameas” definitions for columns seem to be mistaken 

---

src/tilda/loader/csv/stores/PostgreSQLCSVImporter.java

Fixes: CapsicoHealth/Tilda#129

use 'EXCLUDED' table while upserting in Load Util

---

src/tilda/generation/java8/TildaData.java
src/tilda/generation/java8/TildaFactory.java
src/tilda/parsing/parts/Column.java
src/tilda/parsing/parts/helpers/ValueHelper.java
src/tilda/utils/DateTimeUtil.java

- Added parsing method for local dates in DatetimeUtils
- Added proper LocalDate-based code gen to TildaApp and TildaFactory
- Added ability to set an actual date as default value

#149 improper handling of DATE columns

---

src/tilda/generation/html/TildaDocs.js

Gotta adjust up for columns otherwise they are hidden by the header.

#154 Jumps in docs not accurate

---

src/tilda/loader/csv/stores/PostgreSQLCSVImporter.java

-Fixed logic for code paths when not nullable column has no value

#133 ImportBase fails with not null coulmns defined in model

---

src/tilda/data/_Tilda/TILDA__CONNECTION.java
src/tilda/data/_Tilda/TILDA__FORMULA.java
src/tilda/data/_Tilda/TILDA__FORMULADEPENDENCY.java
src/tilda/data/_Tilda/TILDA__FORMULADEPENDENCYVIEW.java
src/tilda/data/_Tilda/TILDA__FORMULARESULT.java
src/tilda/data/_Tilda/TILDA__FORMULARESULTVIEW.java
src/tilda/data/_Tilda/TILDA__JOBS.java
src/tilda/data/_Tilda/TILDA__JOB_DETAIL.java
src/tilda/data/_Tilda/TILDA__KEY.java
src/tilda/data/_Tilda/TILDA__MAINTENANCE.java
src/tilda/data/_Tilda/TILDA__MAPPING.java
src/tilda/data/_Tilda/TILDA__MEASURE.java
src/tilda/data/_Tilda/TILDA__MEASUREFORMULA.java
src/tilda/data/_Tilda/TILDA__MEASUREFORMULAVIEW.java
src/tilda/data/_Tilda/TILDA__OBJECTPERF.java
src/tilda/data/_Tilda/TILDA__REFILLPERF.java
src/tilda/data/_Tilda/TILDA__TESTING.java
src/tilda/data/_Tilda/TILDA__TESTING_Json.java
src/tilda/data/_Tilda/TILDA__TRANSPERF.java
src/tilda/data/_Tilda/TILDA__ZONEINFO.java
src/tilda/data/_tilda.Tilda.json
src/tilda/enums/ColumnType.java
src/tilda/enums/NVPData.java
src/tilda/enums/NVPSourceType.java
src/tilda/enums/NVPType.java
src/tilda/enums/OutputFormatType.java
src/tilda/generation/java8/Helper.java
src/tilda/generation/java8/TildaData.java
src/tilda/generation/java8/TildaJson.java
src/tilda/parsing/parts/OutputMapping.java

Added toNVP to TildaJson. 
One piece that I've broken out is the dynamic data type definition for the toNVP maps. Currently they are hard coded to Map<String, Double> to address the immediate need.

#189 add to nvp methods to gen

---

src/tilda/db/stores/PostgreSQL.java
src/tilda/parsing/parts/ViewRealize.java

#198  - indices in realize are not checked for uniqueness
#199  - tables with DATE[] columns cannot be reversed engineered and block Migration

#198 realize indices and unknown database type fo arrays

---

docs/chrome-extension/js/core/helpers.js
docs/chrome-extension/js/core/relation_renderer.js

Tilda visualizer bug fixes #216

---

src/tilda/generation/postgres9/Sql.java
src/tilda/parsing/parts/View.java
src/tilda/parsing/parts/ViewColumn.java

#235 #206 allow for blocking columns, and redefine with formula

---

src/tilda/utils/TextUtil.java
ut/tilda/utils/TextUtilTest.java

+ more test cases for performance.

#238 added startsWith and endsWith logic

---

src/tilda/data/_Tilda/TILDA__CONNECTION.java
src/tilda/data/_Tilda/TILDA__DEPENDENCYDDLDUMMYTABLE.java
src/tilda/data/_Tilda/TILDA__FORMULA.java
src/tilda/data/_Tilda/TILDA__FORMULADEPENDENCY.java
src/tilda/data/_Tilda/TILDA__FORMULADEPENDENCYVIEW.java
src/tilda/data/_Tilda/TILDA__FORMULARESULT.java
src/tilda/data/_Tilda/TILDA__FORMULARESULTVIEW.java
src/tilda/data/_Tilda/TILDA__JOBS.java
src/tilda/data/_Tilda/TILDA__JOB_DETAIL.java
src/tilda/data/_Tilda/TILDA__KEY.java
src/tilda/data/_Tilda/TILDA__MAINTENANCE.java
src/tilda/data/_Tilda/TILDA__MAPPING.java
src/tilda/data/_Tilda/TILDA__MEASURE.java
src/tilda/data/_Tilda/TILDA__MEASUREFORMULA.java
src/tilda/data/_Tilda/TILDA__MEASUREFORMULAVIEW.java
src/tilda/data/_Tilda/TILDA__OBJECTPERF.java
src/tilda/data/_Tilda/TILDA__REFILLPERF.java
src/tilda/data/_Tilda/TILDA__TESTING.java
src/tilda/data/_Tilda/TILDA__TESTING2VIEW.java
src/tilda/data/_Tilda/TILDA__TESTING2VIEW_Factory.java
src/tilda/data/_Tilda/TILDA__TESTINGVIEW.java
src/tilda/data/_Tilda/TILDA__TRANSPERF.java
src/tilda/data/_Tilda/TILDA__ZONEINFO.java
src/tilda/data/_Tilda/TILDA___Docs.TILDA.html
src/tilda/data/_Tilda/TILDA___PostgreSQL.TILDA.sql
src/tilda/data/_tilda.Tilda.json
src/tilda/generation/html/Docs.java
src/tilda/generation/postgres9/Sql.java
src/tilda/parsing/parts/View.java
ut/tilda/data_test/_tilda.TildaTest.json

#243 prevents infinite loops in formula references

#243 infinite fornula loop prevention

---

docs/chrome-extension/js/core/parser.js
docs/chrome-extension/js/core/relation_renderer.js
docs/chrome-extension/js/templates/tilda_schema/_new.html
docs/chrome-extension/js/views/tilda_schema_view.js

"#216" Tilda visualizer bug fixes #216

---

src/tilda/LineCount.java
src/tilda/generation/postgres9/Sql.java
src/tilda/loader/parser/DataObject.java
src/tilda/parsing/parts/Base.java

- also fixed a couple of minor nullPtrs

#265 Invalid group by generated

---

src/tilda/db/stores/PostgreSQL.helpers-start.sql
src/tilda/generation/postgres9/Sql.java

Also quick fix on Tilda.CompareTables()

#288 Subrealize breaks mappings

---

src/tilda/db/metadata/IndexMeta.java
src/tilda/db/stores/DBType.java
src/tilda/db/stores/IBMDB2.java
src/tilda/db/stores/MSSQL.java
src/tilda/db/stores/PostgreSQL.java
src/tilda/generation/interfaces/CodeGenSql.java
src/tilda/generation/postgres9/Sql.java
src/tilda/parsing/parts/Base.java
src/tilda/parsing/parts/Column.java
src/tilda/parsing/parts/Field.java
src/tilda/parsing/parts/ForeignKey.java
src/tilda/parsing/parts/Formula.java
src/tilda/parsing/parts/Index.java
src/tilda/parsing/parts/PrimaryKey.java
src/tilda/parsing/parts/Schema.java
src/tilda/parsing/parts/ViewColumn.java
src/tilda/parsing/parts/ViewRealize.java

Covered view/table, column/viewColumn, index/fk names
#196

#196 Column/Table name size limit

---

src/tilda/generation/java8/TildaFactory.java

- LOG.warn instead of throw
- cleaned up logging.

#329 change mapping initializtion

---

src/tilda/db/QueryHelper.java

One should be allowed to have an order by in a query without a where
clause.

#331 no order by without where clause

---

src/tilda/generation/html/Docs.java
src/tilda/generation/java8/Helper.java
src/tilda/parsing/parts/Formula.java
src/tilda/parsing/parts/View.java
src/tilda/utils/JSONUtil.java

#338 docs enhancements

---

tooling/chrome-extension/output/css/custom.css
tooling/chrome-extension/output/js/core/custom_element_view.js
tooling/chrome-extension/output/js/core/custom_object_collection.js
tooling/chrome-extension/output/js/core/helpers.js
tooling/chrome-extension/output/js/core/parser.js
tooling/chrome-extension/output/js/templates/tilda_schema_view.html
tooling/chrome-extension/output/js/views/tilda_schema_view.js

Changes are,
1) Show removed elements in Table
2) Add search for filtering removed elements
3) Extend "double-click to highlight dependents" to removed elements.

Tilda tooling enhancements

---

src/tilda/generation/html/DocGen.java
src/tilda/generation/html/Docs.java
src/tilda/generation/html/UrlMaker.java
src/tilda/generation/postgres9/Sql.java
src/tilda/parsing/parts/Formula.java
src/tilda/parsing/parts/View.java
src/tilda/parsing/parts/ViewColumn.java

Fixes for #356, #348 and #353.

#356 documentation index html file

---

src/tilda/enums/ColumnType.java
src/tilda/generation/java8/TildaJson.java
src/tilda/generation/postgres9/Sql.java
src/tilda/migration/Migrator.java
src/tilda/parsing/parts/View.java
src/tilda/parsing/parts/ViewColumn.java
src/tilda/utils/DateTimeUtil.java

Handles the main feature as well as 3 bug fixes:
#363 New feature to add "expression" capabilities to view columns
#396 Negative default values are not see by migration steps and cause migration to always occue over and over again.
#395 GroupBy logic for aggregate views change from column name-based to 1,2,3,4... based.
#394 XXX_Json.Write() method doesn't handle not-null columns with number defaults

#363 viewcolumn expression

---

src/META-INF/MANIFEST.MF
src/tilda/db/processors/ObjectProcessor.java
src/tilda/db/processors/RecordProcessor.java
src/tilda/generation/java8/TildaFactory.java
src/tilda/generation/postgres9/Sql.java
src/tilda/parsing/parts/Object.java
src/tilda/parsing/parts/Query.java
ut/tilda/tutorial/data/Test_Realized_Data.java
ut/tilda/tutorial/data/Test_XYZ_Analytics_Realized_Data.java
ut/tilda/tutorial/data/Test_XYZ_Realized_Data.java

#349 orderby output with full column names
#471 enhance RecordProcessor and ObjectProcessor interfaces
#470 flagging duplicate names across indices AND queries
#347 Streaming version of query-based lookup methods

#349 orderby output needs to be better qualified

---

src/tilda/Docs.java
src/tilda/Gen.java
src/tilda/Import.java
src/tilda/Migrate.java
src/tilda/db/ConnectionPool.java
src/tilda/db/DeleteQuery.java
src/tilda/db/JDBCHelper.java
src/tilda/db/MasterFactory.java
src/tilda/db/SequencePoll.java
src/tilda/db/stores/PostgreSQL.helpers-start.sql
src/tilda/db/stores/PostgreSQL.java
src/tilda/enums/AggregateType.java
src/tilda/generation/java8/Helper.java
src/tilda/generation/postgres9/Sql.java
src/tilda/parsing/ParserSession.java
src/tilda/parsing/parts/Index.java
src/tilda/utils/DurationUtil.java
src/tilda/utils/LogUtil.java

#498 left anchored like indexing support

---

.classpath
src/tilda/Load.java
src/tilda/db/Connection.java
src/tilda/db/JDBCHelper.java
src/tilda/db/processors/StringStringListRP.java
src/tilda/db/stores/PostgreSQL.helpers-start.sql
src/tilda/generation/java8/TildaData.java
src/tilda/generation/java8/TildaFactory.java
src/tilda/loader/parser/Config.java
src/tilda/loader/parser/DataObject.java
src/tilda/migration/actions/DDLDependencyPreManagement.java
src/tilda/parsing/parts/Base.java
src/tilda/parsing/parts/FormulaTemplate.java
src/tilda/parsing/parts/Index.java
src/tilda/parsing/parts/IndexTemplate.java
src/tilda/parsing/parts/ViewPivotValue.java
src/tilda/parsing/parts/ViewRealize.java
src/tilda/parsing/parts/formulaTemplates/Template.java
src/tilda/parsing/parts/formulaTemplates/TemplateExpansion.java
src/tilda/utils/DateTimeUtil.java
src/tilda/utils/EncryptionUtil.java
src/tilda/utils/FileUtil.java
src/tilda/utils/MailUtil.java
src/tilda/utils/TextUtil.java

#555 index templates
#556 short alias
#557 datasetName for Load
#558 adding EncryptionUtil.hmacSHA1
#559 TextUtil.printJsonQuotedStringValue()
#560 pass header name/value pairs in FileUtil.getXXXFromUrl methods
#561 lead not passed in for JSON list methods
#562 update syntax for formulaTemplate TEMPLATE
#563 MailUtil.send doesn't set smtp port correctly
#564 tilda.arrayPick db function
#565 set fetch size in JDBCHelper.executeSelect
#566 DateTimeUtil.printDateTimeForJSON with new forceISOZDT param
#567 savepoint exception when starting application with validation:true
#568 more postgres conversion functions
#569 Code gen for upsert is bad

#555 index templates

---

TildaDocsJar.jardesc
TildaJar.jardesc
src/tilda/enums/AggregateType.java
src/tilda/enums/ColumnType.java
src/tilda/migration/Migrator.java
src/tilda/parsing/parts/Query.java
src/tilda/parsing/parts/TypeDef.java
src/tilda/parsing/parts/helpers/ValueHelper.java
src/tilda/types/Type_NumericPrimitive.java
src/tilda/types/Type_NumericPrimitiveNull.java
src/tilda/utils/TextUtil.java

Also included:
- Quick helper functions on TextUtil
- More detailed parsing error reporting for ReferenceHelper use in
query element
- JAR naming updates for Tilda 2.0.0 for jardesc configurations

#675 NUMERIC enhancements

---

.classpath
.settings/com.google.cloud.tools.eclipse.appengine.libraries/_libraries.container
.settings/com.google.cloud.tools.eclipse.appengine.libraries/master-container.container
.settings/org.eclipse.jdt.core.prefs
src/tilda/db/Connection.java
src/tilda/enums/AggregateType.java
src/tilda/generation/helpers/TotalMess.java
src/tilda/generation/html/Docs.java
src/tilda/generation/java8/TildaData.java
src/tilda/generation/postgres9/Sql.java
src/tilda/parsing/parts/Column.java
src/tilda/parsing/parts/OrderBy.java
src/tilda/utils/LogUtil.java
src/tilda/utils/json/JSONUtil.java
ut/tilda/data_test/_Tilda/TILDA__TESTING_CLONED_Factory.java
ut/tilda/data_test/_Tilda/TILDA__TESTING_Factory.java

+ project config updates/cleanups
+ new helper "nothrow" methods for Connection
+ nullPtr exception in TotalMess if missing comma in FK json definitions
+ nullPtr exception in Docs if missing comma in joins json definitions
+ fix for BigDecimal constants
+ nullptr when outputting null raw json data from JSONUtil
+ LogUtil.logThrowables() helper method

#520 aggregate order-by enhancements

---

src/tilda/db/Connection.java
src/tilda/db/metadata/SchemaMeta.java
src/tilda/db/stores/MSSQL.java
src/tilda/db/stores/PostgreSQL.helpers-start.sql
src/tilda/db/stores/PostgreSQL.java
src/tilda/enums/AggregateType.java
src/tilda/enums/ColumnType.java
src/tilda/enums/FrameworkColumnType.java
src/tilda/generation/graphviz/GraphvizUtil.java
src/tilda/generation/html/DocGen.java
src/tilda/generation/java8/TildaData.java
src/tilda/generation/java8/TildaFactory.java
src/tilda/generation/postgres9/Sql.java
src/tilda/grammar/servlets/TildaSQLServlet.java
src/tilda/parsing/parts/Column.java
src/tilda/parsing/parts/OrderBy.java
src/tilda/parsing/parts/ViewColumn.java
src/tilda/parsing/parts/ViewJoinSimple.java
src/tilda/parsing/parts/helpers/PivotHelper.java
src/tilda/parsing/parts/helpers/ValueHelper.java
src/tilda/utils/DateTimeUtil.java
ut/tilda/parsing/parts/AggregateRangeTest.java

Covers the following related
#678: Window Functions such as ROW_NUMBER, LAG and LEAD...
#687: Aliases for column and aggregate types, e.g., BIGINT/LONG, ROWNUM/ROW_NUMBER...
#688: Partition by on aggregates
#689: Window ranges on aggregates

#678 window functions

---

src/tilda/Load.java
src/tilda/db/QueryHelper.java
src/tilda/generation/java8/TildaFactory.java
src/tilda/loader/csv/stores/PostgreSQLCSVImporter.java
src/tilda/utils/DateTimeUtil.java
ut/tilda/utils/DateTimeUtilTest.java

#678 Misc API updates and cleanups for Window Function feature

---

src/tilda/Import.java
src/tilda/db/stores/MSSQL.java
src/tilda/db/stores/PostgreSQL.helpers-start.sql
src/tilda/db/stores/PostgreSQL.java
src/tilda/enums/AggregateType.java
src/tilda/generation/Generator.java
src/tilda/generation/interfaces/CodeGenDocs.java
src/tilda/generation/interfaces/CodeGenTildaData.java
src/tilda/generation/java8/Docs.java
src/tilda/generation/java8/Helper.java
src/tilda/generation/java8/TildaData.java
src/tilda/generation/java8/TildaFactory.java
src/tilda/generation/postgres9/Sql.java
src/tilda/migration/Migrator.java
src/tilda/parsing/parts/Base.java
src/tilda/parsing/parts/Column.java
src/tilda/parsing/parts/ColumnEnum.java
src/tilda/parsing/parts/ColumnMapper.java
src/tilda/parsing/parts/Enumeration.java
src/tilda/parsing/parts/MappingColumn.java
src/tilda/parsing/parts/Mask.java
src/tilda/parsing/parts/Object.java
src/tilda/parsing/parts/View.java
src/tilda/parsing/parts/ViewColumn.java
src/tilda/parsing/parts/helpers/ValueHelper.java
src/tilda/utils/TextUtil.java
src/tilda/utils/json/gson_serializers/GSONSerializerInitializer.java
src/tilda/utils/json/gson_serializers/GSONSerializer_LocalDate.java
src/tilda/utils/json/gson_serializers/GSONSerializer_LocalDateTime.java

#700 array_cat_agg(anyarray) not compatible in PG14
#699 GSON type adapters for modern JDKs
#698 ValueHelper cleanups
#697 TILDA.array_sort DB helper function
#696 value masking
#687 updated aliases for aggregate types

#696 value masking

---

src/tilda/Export.java
src/tilda/db/processors/ExporterJSONObjectProcessor.java

Allow to target any table in BQ for an export.

#702 bq export enhancements
